# import = ["~/c/deyis-project/.sesh.toml"]

# [default_session]
# startup_command = "nvim"
[default_session]
# startup_command = "nvim -c ':Telescope find_files'"
# startup_command = "v"

# TODO: potential feature ideas
# [[session]]
# name = "session"
# path = "~/path/to/session"
# startup_script = "~/git_repos/dotfiles/sesh/bin/spotify.sh"
# detached = true # never attach to this session, just create it in the background
# tmuxp = "~/.config/tmux/tmuxp/joshmedeski.com.yml"
# tmuxinator = "~/.config/tmux/tmuxinator/joshmedeski.com.yml"

# [[session]]
# name = "karabiner elements"
# path = "~/c/dotfiles/.config/karabiner"
#
# [[session]]
# name = "perplexica"
# path = "~/c/perplexica"
# startup_command = "docker compose up -d"

[[session]]
name = "Home ğŸ¡"
path = "usr"
# startup_command = "z"
# startup_command = "nvim"

# [[session]]
# name = "code ğŸ’»"
# path = "~/PlayCodeChess/"
# startup_command = "ls"


[[session]]
name = "zen ğŸ¯"
path = "~/satori"

[[session]]
name = "dotzen ğŸŒ„"
path = "~/dotzen"

[[session]]
name = "nix-darwin ğŸŒ‡"
path = "~/dotzen/nix-darwin"

[[session]]
name = "codingNote ğŸ“š"
path = "~/satori/note/code"

[[session]]
name = "Stamford ğŸŒŒ"
path = "~/satori/note/stamford"

[[session]]
name = "Note â›©ï¸"
path = "~/satori/note/ntn"

[[session]]
name = "Local ğŸŒ‹"
path = "~/.local"



[[session]]
name = "second brain ğŸ§ "
path = "~/satori/note"
# startup_command = "nvim +ObsidianToday"
# startup_command = "nvim"


# tmuxp = "~/c/dotfiles/.config/tmux/tmuxp-tmux.yml"
# tmuxp = "/Users/joshmedeski/c/dotfiles/.config/tmux/tmuxp-tmux.yml"
# startup_command = "nvim tmux.conf"
#
# [[session]]
# name = "gitmux config"
# path = "~/c/dotfiles/.config/tmux"
# startup_command = "nvim gitmux.conf"
#
# [[session]]
# name = "hammerspoon config"
# path = "~/c/dotfiles/.hammerspoon"
#
# [[session]]
# name = "update"
# path = "/tmp"
# startup_command = "update"
#
[[session]]
name = "neovim config ğŸŒƒ"
path = "~/dotzen/nvim"
# startup_command = "nvim"



[[session]]
name = "shoshinvim config ğŸŒŠ"
path = "~/dotzen/ShoshiNvim"
# startup_command = "nvim"

#
# [[session]]
# name = "fish config"
# path = "~/.config/fish"
# startup_command = "nvim config.fish"
#
# [[session]]
# name = "yazi config"
# path = "~/c/dotfiles/.config/yazi"
# startup_command = "nvim yazi.toml"
#
# [[session]]
# name = "wezterm config"
# path = "~/.config/wezterm"
# startup_command = "nvim wezterm.lua"
#
# [[session]]
# name = "nutiliti new worktree"
# path = "~/c/nu"
# # TODO: auto-close this session when the worktree has been created successfully?  
# # TODO: append [[session]] ./nu/{name}/package/* to this config for dev mode bonus
# startup_commad = "nu_new_worktree"
#
# [[session]]
# name = "second brain ğŸ§ "
# path = "~/obsedian/NGNl/"
# startup_command = "nvim +ObsidianToday"
# startup_command = "nvim"
# #

# [[session]]
# name = "sesh config"
# path = "~/.config/sesh"
# startup_command = "nvim sesh.toml"
#
# [[session]]
# name = "my custom binaries"
# path = "~/c/dotfiles/.config/bin"
#
# [[session]]
# name = "dotfiles"
# path = "~/c/dotfiles"
# startup_command = "lazygit"
# # startup_command = "u"
#
# [[session]]
# name = "blog posts"
# path = "~/c/joshmedeski.com/src/content/posts"
#
# [[session]]
# path = "~/c/joshmedeski.com"
# startup_script = "~/.config/sesh/scripts/node_dev"
#
# [[session]]
# session_path = "~/c/nu/main/packages/*"
# script_path = "~/.config/sesh/scripts/node_dev"


# TODO: implement this 
# script_command = "nvim ~/.tmux"

# [[session]]
# name = "tmux-fzf-url ğŸ–‡ï¸"
# path = "~/.config/tmux/plugins/tmux-fzf-url"
# startup_command = "nvim fzf-url.sh"
#
# [[session]]
# name = "Downloads ğŸ“¥"
# path = "~/Downloads"
# startup_command = "yazi"
#
# [[session]]
# name = "lazy plugins"
# path = "~/.local/share/nvim/lazy"
# startup_command = "sesh connect (ls | fzf --no-border --preview 'glow -s auto {}/README.md') && exit"
